In [1]:
import pandas as pd
import numpy as np

# https://jpvdp.github.io/NetworkIsLife/DAFS_prog_week_1_python.html

exercises from https://jpvdp.github.io/NetworkIsLife/DAFS_prog_week_2_Python.html

# part 1

In [2]:
zeros = np.zeros((4,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
type(zeros)

numpy.ndarray

The variable name is zeros. It stores an object of type numpy.ndarray, a 4*4 matrix of integers.  Note that it is not of type https://numpy.org/doc/stable/reference/generated/numpy.matrix.html


In [4]:
my_number = 10

the variable name is 'my_number'

In [5]:
my_number = 20

In [6]:
my_number


20

# Part 2 

Variables can be reassigned

for each item in the array, add 5:



In [7]:
fives = zeros + 5

In [8]:
fives

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

multiply the matrix by itself:

In [9]:
zeros * zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Part 3


In [10]:
giraffe = 9
rabbit = 4

In [11]:
type(giraffe)

int

In [12]:
type(rabbit)

int

In [13]:
horse = "nine"
cow = "four"

In [14]:
type(horse)


str

In [15]:
type(cow)

str

We convert the number to a string an then check that it has indeed been 'misinterpreted' 

In [16]:
giraffe = str(giraffe) # remember to reassign it 


In [17]:
isinstance(giraffe, int)

False

# Part 4

In [18]:
# assignment
x= 9
y = 4

In [19]:
# check for equality:


x == y

False

In [20]:
a = 1
b = 99999999999


In [21]:
# check for inequality:
a != b

True

In [22]:
Temperature  = 21
Humidity = 49

In [23]:
isComfortable = Temperature > 20 and Humidity < 50

In [24]:
isComfortable

True

# Part 5

In [25]:
import random
x = random.uniform(4,87)
f"The generated number is {x}"

'The generated number is 80.7445112823755'

In [26]:
y = random.randint(4,10)
f"The generated integer is {y}"

'The generated integer is 6'

In [27]:
a= 4
b = 5

f"The sum of a and b is {a+b}"



'The sum of a and b is 9'

In [28]:
f"The difference between a and b is {b-a}"


'The difference between a and b is 1'

In [29]:
f"The product between a and b is {b*a}"


'The product between a and b is 20'

In [30]:
f"The quotient between a and b is {b/a}"

'The quotient between a and b is 1.25'

In [31]:
x = 9
y = 10

f"It is {x>y} that x is greater than y"

'It is False that x is greater than y'

In [32]:
# Create a new numpy array

data = np.array([1,2,3,4])
data.shape

(4,)

In [33]:
data_reshaped = data.reshape(2,2)

In [34]:
data_reshaped

array([[1, 2],
       [3, 4]])

# Part 6 - Functions

No exercises for this part 

# Part 7 - Exercises



not done
