# solutions to exercises at https://jpvdp.github.io/NetworkIsLife/DAFS_prog_week_2_Python.html#exercice-part-6

In [51]:
import pandas as pd

## Part 1


In [52]:
# Part 1

# Carbon emissions checker 
emissions = 21  # tons # <--- Add emissions here 

if emissions < 2:
    print("Low emissions")
elif emissions < 6 and emissions > 2:
    print("Moderate Emissions")
elif emissions < 15 and emissions > 6:
    print("High EMissions")
else:
    print("Very high emissions")


Very high emissions


In [53]:
# Water conservation tracker

usage = 110  # tons # <--- Add emissions here 

if usage < 50:
    print("Excellent conservation")
elif usage < 100 and usage > 50:
    print("Good Conservation")
elif usage < 150 and usage > 100:
    print("Average Conservation")
else:
    print("Poor conservation")

Average Conservation


In [54]:
# Part 2 - importing csvs



df = pd.read_csv('data/EU_countries_population_pollution.csv')

df.head()


Country  Population  Mean_pollution
0   Austria     8859000            11.3
1   Belgium    11456000            11.0
2  Bulgaria     7000000            18.0
3   Croatia     4076000            14.7
4    Cyprus     1213000            14.7

In [55]:


df = pd.read_csv('data/EU_countries_GDP.tsv', sep='\t')

df.head()


Country  GDP_USD_Billions
0   Austria               500
1   Belgium               600
2  Bulgaria                80
3   Croatia                70
4    Cyprus                30

In [56]:
pd.read_json('data/EU_countries_water_pollution.json')

Country  Water_Bodies_in_Poor_Condition_Percentage
0       Austria                                         40
1       Belgium                                         70
2      Bulgaria                                         60
3       Croatia                                         30
4        Cyprus                                         50
5       Czechia                                         55
6       Denmark                                         45
7       Estonia                                         35
8       Finland                                         25
9        France                                         65
10      Germany                                         60
11       Greece                                         50
12      Hungary                                         55
13      Ireland                                         40
14        Italy                                         70
15       Latvia                                         35
16    Lithuania                                         40
17   Luxembourg                                         50
18        Malta                                         45
19  Netherlands                                         65
20       Poland                                         60
21     Portugal                                         50
22      Romania                                         55
23     Slovakia                                         50
24     Slovenia                                         35
25        Spain                                         60
26       Sweden                                         30

In [57]:
# Create a dictionary:

import pandas as pd
# create a dictionary 

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'Score': [85.5, 91.2, 78.3]
}

df = pd.DataFrame(data)
df

Name  Age  Score
0    Alice   24   85.5
1      Bob   27   91.2
2  Charlie   22   78.3

In [58]:
# create a matrix:

import numpy as np
np_matrix = np.matrix([[1, 2, 3], [4, 5, 6], [7,8,9]]) # 'list list'

In [59]:
# 10 by 10 matrix filled with 1s:

ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [60]:
ones * 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [61]:
int(sum(sum(ones)))

100

In [62]:
random_3x3 = np.random.rand(3,3) # this is so inconsistent with np.ones((10,10)) where you need to insert tuple
random_3x3

array([[0.51998735, 0.57989183, 0.17840375],
       [0.53136994, 0.80630827, 0.48373524],
       [0.85279313, 0.80193091, 0.16988553]])

In [63]:
# Create a little matrix


# create a dictionary 

data = {
    'ID': [1, 2, 3],
    'Country': ["NL", "BE", "FR"],
    'Value': [1340.90, 142.23, 821.42]
}

df = pd.DataFrame(data)
df

# Not sure what question 4 refers to but you can multiply dfs like df["Value"] * df["ID"]

ID Country    Value
0   1      NL  1340.90
1   2      BE   142.23
2   3      FR   821.42

# Merging dataframes



In [64]:

data1 = pd.DataFrame( {"Country": ["NL", "DE", "FR"],
       "Pollution": [21,23,17]})
data2 = pd.DataFrame({"Country": ["NL", "DE", "FR"],
       "Population": [17, 84,68]})

data1

Country  Pollution
0      NL         21
1      DE         23
2      FR         17

In [65]:
data2

Country  Population
0      NL          17
1      DE          84
2      FR          68

In [66]:
merged = pd.merge(data1, data2, on = "Country")
merged

Country  Pollution  Population
0      NL         21          17
1      DE         23          84
2      FR         17          68

In [67]:

# Filtering

import pandas as pd
# create a small dataframe
data = {
  'Pat_num': ["WO200214562", "WO2023738962", "EP2023778962", "FR2019272698", "FR201922671"],
  'Year': [2002, 2023, 2023, 2019, 2019],
  'Domain': ["B60C", "B60C", "B29D", "C08K", "C08K"]
}
df = pd.DataFrame(data)
df


Pat_num  Year Domain
0   WO200214562  2002   B60C
1  WO2023738962  2023   B60C
2  EP2023778962  2023   B29D
3  FR2019272698  2019   C08K
4   FR201922671  2019   C08K

In [68]:
# subset the dataframe to extract only patents from 2023
subset = df[df['Year'] == 2023]
print(subset)

        Pat_num  Year Domain
1  WO2023738962  2023   B60C
2  EP2023778962  2023   B29D


In [69]:
# subset the dataframe to extract patent in domain "B60C"
# with year >= 2019
subset = df[(df['Year'] >= 2019) & (df['Domain'] == "B60C")]
print(subset)


        Pat_num  Year Domain
1  WO2023738962  2023   B60C
